# AndroidX Support Enabled
android.useAndroidX=true
# Force-disable configuration cache to shake off stale cached container states
org.gradle.configuration-cache=false

org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=320m -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.daemon=false
org.gradle.parallel=false

